############
# Settings #
############

# Display health, magicka and stamina values for the player
bShowPlayerValues = true

# Display health values for regular enemies
bShowEnemyValues = true

# Display health values for bosses
bShowBossValues = true