############
# Settings #
############

# Display health, magicka and stamina values for the player
bShowPlayerValues = false

# Display health values for regular enemies
bShowEnemyValues = false

# Display health values for bosses
bShowBossValues = false